# Generated by Django 6.0.5 on 2026-06-23 06:52

import django_smartbase_admin.messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb_admin_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=django_smartbase_admin.messaging.models.message_attachment_storage, upload_to=django_smartbase_admin.messaging.models.message_attachment_upload_to, verbose_name='File'),
        ),
    ]
