# Generated by Django 5.2.8 on 2026-06-23 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('request_size', models.PositiveIntegerField(default=0, help_text='Serialized size of the input payload in bytes.')),
                ('response_size', models.PositiveIntegerField(default=0, help_text='Serialized size of the response in bytes.')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('result_status', models.CharField(blank=True, max_length=32)),
                ('result_count', models.IntegerField(blank=True, null=True)),
                ('result_total', models.IntegerField(blank=True, null=True)),
                ('result_fields', models.IntegerField(blank=True, null=True)),
                ('result_inlines', models.IntegerField(blank=True, null=True)),
                ('result_inline_rows', models.IntegerField(blank=True, null=True)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('error_type', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCP Request Log',
                'verbose_name_plural': 'MCP Request Logs',
                'db_table': 'sbadmin_mcp_log_request',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tool_name', 'timestamp'], name='sbadmin_mcp_tool_na_c69a0c_idx'), models.Index(fields=['user', 'timestamp'], name='sbadmin_mcp_user_id_664d1a_idx'), models.Index(fields=['is_error', 'timestamp'], name='sbadmin_mcp_is_erro_bcf73d_idx')],
            },
        ),
    ]
