# Generated by Django 5.2.8 on 2026-06-24 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time')),
                ('tool_name', models.CharField(db_index=True, max_length=64, verbose_name='Tool')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Request')),
                ('request_size', models.PositiveIntegerField(default=0, help_text='Serialized size of the input payload in bytes.', verbose_name='Request size (B)')),
                ('response_size', models.PositiveIntegerField(default=0, help_text='Serialized size of the response in bytes.', verbose_name='Response size (B)')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duration (ms)')),
                ('result_status', models.CharField(blank=True, max_length=32, verbose_name='Result status')),
                ('result_total', models.IntegerField(blank=True, null=True, verbose_name='Record count')),
                ('result_fields', models.IntegerField(blank=True, null=True, verbose_name='Returned field count')),
                ('result_inlines', models.IntegerField(blank=True, null=True, verbose_name='Returned inline count')),
                ('result_inline_rows', models.IntegerField(blank=True, null=True, verbose_name='Returned inline rows')),
                ('is_error', models.BooleanField(db_index=True, default=False, verbose_name='Error')),
                ('error_type', models.CharField(blank=True, max_length=128, verbose_name='Error type')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'MCP Request Log',
                'verbose_name_plural': 'MCP Request Logs',
                'db_table': 'sbadmin_mcp_log_request',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tool_name', 'timestamp'], name='sbadmin_mcp_tool_na_c69a0c_idx'), models.Index(fields=['user', 'timestamp'], name='sbadmin_mcp_user_id_664d1a_idx'), models.Index(fields=['is_error', 'timestamp'], name='sbadmin_mcp_is_erro_bcf73d_idx')],
            },
        ),
    ]
