# Generated by Django 5.2.11 on 2026-02-10 09:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, help_text='Groups changes from the same request together', null=True)),
                ('object_id', models.TextField(blank=True)),
                ('object_repr', models.CharField(max_length=255)),
                ('parent_object_id', models.TextField(blank=True)),
                ('parent_object_repr', models.CharField(blank=True, max_length=255)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('bulk_create', 'Bulk Create'), ('bulk_update', 'Bulk Update'), ('bulk_delete', 'Bulk Delete')], max_length=20)),
                ('snapshot_before', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('is_bulk', models.BooleanField(db_index=True, default=False)),
                ('bulk_count', models.IntegerField(default=0)),
                ('affected_objects', models.JSONField(blank=True, default=list)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('parent_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'sb_admin_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='sb_admin_au_content_61a586_idx'), models.Index(fields=['parent_content_type', 'parent_object_id'], name='sb_admin_au_parent__d412b1_idx'), django.contrib.postgres.indexes.GinIndex(fields=['affected_objects'], name='sb_admin_au_affecte_d8a4f8_gin'), models.Index(fields=['user', 'timestamp'], name='sb_admin_au_user_id_be1439_idx'), models.Index(fields=['action_type'], name='sb_admin_au_action__03aee4_idx')],
            },
        ),
    ]
