# Generated by Django 5.2.11 on 2026-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb_admin_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
