# Generated by Django 2.2.28 on 2023-04-02 21:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartbase_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sbadminlistviewconfiguration',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='sbadminlistviewconfiguration',
            old_name='urlParams',
            new_name='url_params',
        ),
    ]
