# Generated by Django 2.2.28 on 2023-04-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartbase_admin', '0002_auto_20230402_2316'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sbadminlistviewconfiguration',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='sbadminlistviewconfiguration',
            name='url_params',
            field=models.TextField(),
        ),
    ]
