# Generated by Django 5.0.14 on 2025-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smartbase_admin', '0005_sbadminuserconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbadminuserconfiguration',
            name='color_scheme',
            field=models.CharField(choices=[('auto', 'System'), ('dark', 'Dark'), ('light', 'Light')], default='auto', max_length=255, verbose_name='Theme'),
        ),
    ]
